### ISSUE TITLE
hwo to use adonisjs with livewire

### ISSUE THREAD

**Issue by ramabie** [KABBOUCHI/adonisjs-livewire#1]
```ts
import { Component } from 'adonisjs-livewire'

export default class Counter extends Component {
    public count = 0

    public increment() {
        this.count++
    }

    public decrement() {
        this.count--
    }

    public render()
    {
        // how ?
    }
}
```
-----------------------------

```blade
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> AdonisJS - A fully featured web framework for Node.js </title>

  @vite(['resources/css/app.css', 'resources/js/app.js'])

  @livewireStyles
</head>
<body>
  <h1> It Works! </h1>
  <br>
<div>

  <livewire:counter />
</div>

  @livewireScripts
</body>
</html>
```
--------------

 Error
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

**Comment by KABBOUCHI** [comment]
> // how ?

just return html string or view

with string
```ts
render() {
  return /** html **/`<div>
                <button wire:click="decrement">-</button>   
                <h2>{{ count }}</h2>
                <button wire:click="increment">+</button>
  </div>`
}
```

using edge view

```ts
render() {
 return this.view.render("livewire/counter")
}
```

also u can remove the render func, it will use `livewire/counter` automatically 


>Error
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

i only tested on macOS and linux, will try to check on my windows machine

**Comment by ramabie** [comment]
after I cloned this repo example: https://github.com/KABBOUCHI/adonisjsv6-livewire-demo, I still encountered the same error

![image](https://github.com/KABBOUCHI/adonisjs-livewire/assets/9291941/a76a6255-4b26-45e9-93a8-74d31883d656)

**Comment by KABBOUCHI** [comment]
I just pushed the fix for windows, plz pull and update, should work now

**Comment by ramabie** [comment]
wow great...
thank you very much now it works,

this will be a very interesting piece.
