### ISSUE TITLE
how to parsing data to Layout

### ISSUE THREAD

**Issue by ramabie** [KABBOUCHI/adonisjs-livewire#3]
like this

![image](https://github.com/KABBOUCHI/adonisjs-livewire/assets/9291941/d7507d1c-1489-4330-a7e7-fe22cf752ec0)

![image](https://github.com/KABBOUCHI/adonisjs-livewire/assets/9291941/89040012-912b-42be-bac6-1fd4c00d5ea1)

**Comment by KABBOUCHI** [comment]
u can now pass props to component on the latest version

```ts
@layout('components/layouts/main', {
  sidebar: true,
})
```

**Comment by ramabie** [comment]
Excellent ...
Excellent

Thank you very much
