### ISSUE TITLE
sub folder in livewire and create layout

### ISSUE THREAD

**Issue by ramabie** [KABBOUCHI/adonisjs-livewire#4]
how to use sub folder in livewire?

like this?
php artisan make:livewire users.category-index

node ace make:livewire  users.category-index

and this also doesn't work

node ace livewire:layout app
node ace livewire:layout guest

**Comment by KABBOUCHI** [comment]
@ramabie both commands has been fixed https://github.com/KABBOUCHI/adonisjsv6-livewire-demo/commit/4a80abeee45704943865c6576ec6dcc72c3336d1
