### ISSUE TITLE
Error: ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by ramabie** [KABBOUCHI/adonisjs-livewire#6]
![image](https://github.com/user-attachments/assets/1aa300c4-8f3d-418e-a941-679cf7c1cdb3)

OS: windows 11
node : v21.7.3
npm: 8.3.0

**Comment by KABBOUCHI** [comment]
make sure u have the latest version and rename `adonisjs-livewire/edge_provider` to `adonisjs-livewire/view_provider/view_provider`
